### PR TITLE
Auto-refresh for cameras

### PR DESCRIPTION
**Pull request by maros**
This PR adds auto-refresh for camera devices. The camera module must enable this behaviour by setting metrics:autoRefresh to true

### CODE REVIEW

**Comment by maros** [comment]
@vades did you close the PR because it was against the wrong branch, or because of technical/product management/... issues? Should I re-open it against dev or make any amendments?

**Comment by vades** [comment]
For what type of cameras is this needed? Please can you describe more acurrate why is this needed?

**Comment by maros** [comment]
When I open a camera that servers static (eg. jpeg) images in the UI, the image from the camera is loaded only once. Whenever I reopen the camera popover I get the same image - no reloading takes place because the image is already loaded. I need to reload the whole UI to get a fresh camera still. This PR adds a cache buster to the url, and changes it in regular intervals to trigger reloading of the camera image. see https://github.com/maros/Zway-RaspberryCam

**Comment by vades** [comment]
Please next pull request to "DEV" branch

**Pull request merged**
